### ISSUE TITLE
能双向通信吗？

### ISSUE THREAD

**Issue by aaaking** [leavesCZY/WifiP2P#21]
手机能既是客户端又是服务端吗？能双向通信吗？

**Comment by leavesCZY** [comment]
@aaaking 老哥你真是锲而不舍。按道理是可以的，只要设置好状态值就行

**Comment by aaaking** [comment]
> @aaaking 老哥你真是锲而不舍。按道理是可以的，只要设置好状态值就行

我也觉得理论上是可行的， 那我实际试下看能不能双向通信

**Comment by leavesCZY** [comment]
> > @aaaking 老哥你真是锲而不舍。按道理是可以的，只要设置好状态值就行
> 
> 我也觉得理论上是可行的， 那我实际试下看能不能双向通信

我有另外一个项目也实现了类似功能，你看对你有用不。https://github.com/leavesCZY/WifiFileTransfer

**Comment by aaaking** [comment]
> > > @aaaking 老哥你真是锲而不舍。按道理是可以的，只要设置好状态值就行
> > 
> > 
> > 我也觉得理论上是可行的， 那我实际试下看能不能双向通信
> 
> 我有另外一个项目也实现了类似功能，你看对你有用不。https://github.com/leavesCZY/WifiFileTransfer

这个我看过了，很好用，但是需要开启Wi-Fi热点，跟我们的产品的场景不一样。我们的产品不能让用户去开启Wi-Fi热点
