### ISSUE TITLE
作者可以加license吗？想在自己的项目里用，又怕有版权风险

### ISSUE THREAD

**Issue by CarpOrange** [leavesCZY/WifiP2P#25]
非常感谢~

**Comment by leavesCZY** [comment]
版权意识都这么强吗😂说实话我一直对这一块不太了解，本来想着就是开源出来给人随意用的。你有这方面的担心的话，有推荐的 license 吗，我后续加上

**Comment by CarpOrange** [comment]
哈哈，商用还是要注意规范的。你可以参考下https://blog.csdn.net/CatherineJChen/article/details/103987526这篇进行选择，文章里面的总结：
中小开源Apache License2.0利于推广

大型开源GPL3.0利于保持后续版本开源

简单开源MIT简单省事没有什么限制条款

**Comment by leavesCZY** [comment]
那看来 MIT LICENSE 对于引用方来说最方便，我已添加 LICENSE 了

**Comment by CarpOrange** [comment]
> 那看来 MIT LICENSE 对于引用方来说最方便，我已添加 LICENSE 了

收到，感谢作者大大
