### ISSUE TITLE
两台设备进行socket连接的时候报错

### ISSUE THREAD

**Issue by a363567557** [leavesCZY/WifiP2P#4]
02-21 18:47:35.748 17664-18111/com.czy.filetransfer E/WifiClientTask: 文件发送异常 Exception: failed to connect to /192.168.49.1 (port 4786) after 1000000ms: isConnected failed: ECONNREFUSED (Connection refused)

请问是什么问题

**Comment by a363567557** [comment]
socket.connect((new InetSocketAddress(strings[0], PORT)), 1000000);

**Comment by leavesCZY** [comment]
已经修复了一些已知问题，你再试下
