### ISSUE TITLE
获取不到P2P设备列表，在手机设置中的wifi直连中就可以扫描到。

### ISSUE THREAD

**Issue by Boucles** [leavesCZY/WifiP2P#6]

**Comment by idashy** [comment]
+1

**Comment by jenkin-du** [comment]
我也是这样，具体回事什么原因

**Comment by OwnerKobe** [comment]
android 6.0+以上需要申请permission.ACCESS_COARSE_LOCATION动态权限，安全起见在清单文件中加入android.permission.ACCESS_FINE_LOCATION。

**Comment by leavesCZY** [comment]
已经修复问题了，你再试下
