### ISSUE TITLE
demo中createGroup方法一直调用不成功

### ISSUE THREAD

**Issue by tp19970424** [leavesCZY/WifiP2P#9]
手机：小米9
版本：android9.0
问题：demo下载下来后在手机上运行，在ReceiveFileActivity中创建群组的回调一直走的是onFailure(),reason返回的值是1，所有的权限也给了

**Comment by leavesCZY** [comment]
已经修复问题了，你再试下

**Comment by tp19970424** [comment]
嗯，好了，可以创建群组了
